# Generated by Django 5.0.1 on 2024-12-09 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_prj', '0003_task_thumbnail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['created'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='place',
        ),
        migrations.AddField(
            model_name='task',
            name='manufacturer',
            field=models.CharField(default=1, max_length=100, verbose_name='Производитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_user', to=settings.AUTH_USER_MODEL, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_task', to='project_prj.task', verbose_name='Заказы'),
        ),
    ]
